### ISSUE TITLE
Display text if stream is offline

### ISSUE THREAD

**Issue by jaaneh** [adrianschofield/twitchuptime#2]
Hey there,

Thanks for the script!

I am using this on a website to display stream uptime, and was wondering if you would add some sort of text that displays "Stream Offline" or similar if it's offline, instead of displaying "00:00:00".

**Comment by adrianschofield** [comment]
Hi jaaneh - sorry it took me a while to get to this but the latest version has a change to do what you wanted, please check the readme and give it a go and let me know if it works or if there are any issues.

Thanks
Adrian
